# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 40100, host: 40100
  config.vm.network "forwarded_port", guest: 40101, host: 40101
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/hifi-ubuntu-dev.yml"
    ansible.sudo_user = "vagrant"
  end
end
